
// Objective-C API for talking to the following Go packages
//
//	github.com/rarimovoting/identity
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Identity_FRAMEWORK_H__
#define __Identity_FRAMEWORK_H__

#include "Identity.objc.h"
#include "Universe.objc.h"

#endif
