// Objective-C API for talking to github.com/rarimovoting/identity Go package.
//   gobind -lang=objc github.com/rarimovoting/identity
//
// File is generated by gobind. Do not edit.

#ifndef __Identity_H__
#define __Identity_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class IdentityAuthV2CircuitInputs;
@class IdentityChainInfo;
@class IdentityClaimDetails;
@class IdentityClaimOfferResponse;
@class IdentityCredentialRequest;
@class IdentityCredentialSchema;
@class IdentityCredentialStatus;
@class IdentityCredentialsRequestBody;
@class IdentityGISTProof;
@class IdentityIdentity;
@class IdentityNodeAuxValue;
@class IdentityTreeState;
@class IdentityVSResponse;
@class IdentityVSResponseBody;
@class IdentityW3CCredential;
@protocol IdentityStateProvider;
@class IdentityStateProvider;

@protocol IdentityStateProvider <NSObject>
- (NSData* _Nullable)fetchW3Credentials:(NSString* _Nullable)url method:(NSString* _Nullable)method body:(NSString* _Nullable)body error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getGISTProof:(NSString* _Nullable)userId error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getProviderChainInfo:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)proveAuthV2:(NSData* _Nullable)inputs error:(NSError* _Nullable* _Nullable)error;
@end

@interface IdentityAuthV2CircuitInputs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull genesisID;
@property (nonatomic) NSString* _Nonnull profileNonce;
// skipped field AuthV2CircuitInputs.AuthClaim with unsupported type: *github.com/iden3/go-iden3-core/v2.Claim

// skipped field AuthV2CircuitInputs.AuthClaimMtp with unsupported type: []*github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.AuthClaimNonRevMtp with unsupported type: []*github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.AuthClaimNonRevMtpAuxHi with unsupported type: *github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.AuthClaimNonRevMtpAuxHv with unsupported type: *github.com/iden3/go-merkletree.Hash

@property (nonatomic) NSString* _Nonnull authClaimNonRevMtpNoAux;
@property (nonatomic) NSString* _Nonnull challenge;
@property (nonatomic) NSString* _Nonnull challengeSignatureR8X;
@property (nonatomic) NSString* _Nonnull challengeSignatureR8Y;
@property (nonatomic) NSString* _Nonnull challengeSignatureS;
// skipped field AuthV2CircuitInputs.ClaimsTreeRoot with unsupported type: *github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.RevTreeRoot with unsupported type: *github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.RootsTreeRoot with unsupported type: *github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.State with unsupported type: *github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.GISTRoot with unsupported type: *github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.GISTMtp with unsupported type: []*github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.GISTMtpAuxHi with unsupported type: *github.com/iden3/go-merkletree.Hash

// skipped field AuthV2CircuitInputs.GISTMtpAuxHv with unsupported type: *github.com/iden3/go-merkletree.Hash

@property (nonatomic) NSString* _Nonnull gistMtpNoAux;
@end

@interface IdentityChainInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t identifier;
@property (nonatomic) NSString* _Nonnull rpcUrl;
@property (nonatomic) NSString* _Nonnull stateContractAddress;
@property (nonatomic) NSString* _Nonnull rarimoNetworkType;
@end

@interface IdentityClaimDetails : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull typ;
@property (nonatomic) NSString* _Nonnull claimType;
@property (nonatomic) NSString* _Nonnull threadID;
// skipped field ClaimDetails.Body with unsupported type: github.com/rarimovoting/identity.claimDetailsBody

@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@end

@interface IdentityClaimOfferResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped constructor ClaimOfferResponse.NewClaimOfferResponse with unsupported parameter or return types

@property (nonatomic) NSString* _Nonnull identifier;
@property (nonatomic) NSString* _Nonnull typ;
@property (nonatomic) NSString* _Nonnull claimType;
@property (nonatomic) NSString* _Nonnull threadID;
// skipped field ClaimOfferResponse.Body with unsupported type: github.com/rarimovoting/identity.CredentialsRequestBody

@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@end

@interface IdentityCredentialRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)description id_:(NSString* _Nullable)id_;
@property (nonatomic) NSString* _Nonnull description;
@property (nonatomic) NSString* _Nonnull identifier;
@end

@interface IdentityCredentialSchema : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull innerType;
@end

@interface IdentityCredentialStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identifier;
@property (nonatomic) NSString* _Nonnull innerType;
// skipped field CredentialStatus.RevocationNonce with unsupported type: *math/big.Int

@property (nonatomic) IdentityCredentialStatus* _Nullable statusIssuer;
@end

@interface IdentityCredentialsRequestBody : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped constructor CredentialsRequestBody.NewCredentialsRequestBody with unsupported parameter or return types

// skipped field CredentialsRequestBody.Credentials with unsupported type: []github.com/rarimovoting/identity.CredentialRequest

@property (nonatomic) NSString* _Nonnull url;
@end

@interface IdentityGISTProof : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

@interface IdentityIdentity : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)privateKeyHex stateProvider:(id<IdentityStateProvider> _Nullable)stateProvider;
- (NSString* _Nonnull)getDID;
- (NSString* _Nonnull)getID:(NSError* _Nullable* _Nullable)error;
- (BOOL)initVerifiableCredentials:(NSData* _Nullable)offerData error:(NSError* _Nullable* _Nullable)error;
// skipped method Identity.PrepareAuth2Inputs with unsupported parameter or return types

@end

@interface IdentityNodeAuxValue : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

@interface IdentityTreeState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

@interface IdentityVSResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field VSResponse.Body with unsupported type: github.com/rarimovoting/identity.VSResponseBody

@end

@interface IdentityVSResponseBody : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field VSResponseBody.Credential with unsupported type: github.com/rarimovoting/identity.W3CCredential

@end

@interface IdentityW3CCredential : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull identifier;
@property (nonatomic) NSString* _Nonnull context;
@property (nonatomic) NSString* _Nonnull innerType;
// skipped field W3CCredential.ExpirationDate with unsupported type: *string

// skipped field W3CCredential.IssuanceDate with unsupported type: *string

// skipped field W3CCredential.CredentialSubject with unsupported type: map[string]interface{}

// skipped field W3CCredential.CredentialStatus with unsupported type: github.com/rarimovoting/identity.CredentialStatus

@property (nonatomic) NSString* _Nonnull issuer;
// skipped field W3CCredential.CredentialSchema with unsupported type: github.com/rarimovoting/identity.CredentialSchema

// skipped field W3CCredential.Proof with unsupported type: map[string]interface{}

@end

// skipped function NewClaimOfferResponse with unsupported parameter or return types


FOUNDATION_EXPORT IdentityCredentialRequest* _Nullable IdentityNewCredentialRequest(NSString* _Nullable description, NSString* _Nullable id_);

// skipped function NewCredentialsRequestBody with unsupported parameter or return types


FOUNDATION_EXPORT IdentityIdentity* _Nullable IdentityNewIdentity(NSString* _Nullable privateKeyHex, id<IdentityStateProvider> _Nullable stateProvider, NSError* _Nullable* _Nullable error);

@class IdentityStateProvider;

@interface IdentityStateProvider : NSObject <goSeqRefInterface, IdentityStateProvider> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSData* _Nullable)fetchW3Credentials:(NSString* _Nullable)url method:(NSString* _Nullable)method body:(NSString* _Nullable)body error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getGISTProof:(NSString* _Nullable)userId error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getProviderChainInfo:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)proveAuthV2:(NSData* _Nullable)inputs error:(NSError* _Nullable* _Nullable)error;
@end

#endif
